Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -131,6 +131,96 @@ archive:
     after_script:
         - echo "Archive development complete..."
 
+deploy:
+    stage: deploy
+    environment:
+        name: development
+        url: http://188.166.214.118:9090
+    tags:
+        - s1
+    before_script:
+        - echo "create Dir backup java"
+        - |
+          if [ -d /backup/agregate_service ]; then 
+            echo "Directory Is exists."; 
+          else 
+            mkdir -p /backup/agregate_service;
+            echo "Create Directory backup Success...";
+          fi
+        - echo "create Dir App java"
+        - |
+          if [ -d $DIR_APP ]; then 
+            echo "Directory Is exists."; 
+          else 
+            mkdir -p $DIR_APP;
+            echo "Create Directory Success...";
+          fi
+        - | 
+          if [ -e "app_`date +%y_%m_%d`.tar.gz" ]; then 
+            echo "Yes, file exists"; 
+          else 
+            echo "Compres Proses..."; 
+            if [[ ! -d "app" ]]
+            then
+                echo "Directory Not Found on your filesystem."
+            else
+                tar -cf /backup/agregate_service/app`date +%y_%m_%d`.tar.gz app 
+                echo "compres success...";
+            fi             
+          fi                
+ 
+    script: 
+        - cd $DIR_RELEASE/agregate_service && pwd
+        - echo "Extract Package...."
+        - |
+          if unzip *.zip 2>/dev/null; then
+            echo 'All is good, archive extracted' >&2;
+          else
+            echo 'Archive failed to extract' >&2;
+            rm -rf $DIR_RELEASE/agregate_service/artifacts.zip;
+            cd $CI_BUILDS_DIR && pwd;
+            zip -r artifacts.zip build/libs && mv artifacts.zip $DIR_RELEASE/agregate_service/;
+          echo "Archiving Package success...!";
+          fi 
+        - unzip artifacts.zip && ls -ltr libs  
+        - echo "kill service java"  
+        - kill -9 java  && ps aux | grep java
+        - echo "kill service success"
+        - echo "Preparing remove packages java..."
+        - rm -rf app 
+        - ls -ltr app 
+        - echo "Remove Package Success..."
+        - mv build/libs /home/appuser01/app 
+        - echo "Clean Up Package..."
+        - rm -rf *
+        - echo "Make Sure Privileges user.."
+        - ls -ltr /home/appuser01/app
+        - chown -R appuser01:appuser01 /home/appuser01/app && chmod -R 755 /home/appuser01/app
+        - echo "Preparing start service java..."
+        - su appuser01 && cd /home/appuser01/app 
+        - java -jar -Dspring.location.config=application.properties springboot-postgresql-0.0.1-SNAPSHOT.jar
+        - ps aux | grep java
+        # && systemctl status agregate.service
+        # - systemctl restart agregate.service && systemctl status agregate.service
+        - echo "deploy Success.."
+        - echo "clean up package after deploy..."
+        - sudo ls -ltr $DIR_RELEASE/agregate_service/
+        - sudo rm -rf $DIR_RELEASE/agregate_service/* && sudo ls -ltr $DIR_RELEASE/agregate_service/
+        - echo "processing clean up success..."
+
+    only:
+        - master        
+
+    retry:
+      max: 2
+      when: always      
+
+    allow_failure: true
+    when: delayed
+    start_in: 1 minutes
+    after_script:
+        - echo "Deploy development complete..."
+
 
     
 
